In [10]:
inputs= [[1, 2, 3, -4, 5], [2, 3, 4, -5, 6], [3, 4, 5, -6, 7]]


weights = [[0.2, 0.4, 0.6, 0.8, -1.0],
           [0.1, 0.3, 0.5, 0.7, -0.9],
           [0.5, 0.4, 0.3, 0.2, 0.1]]

bias = [3, 2, 1]
weights2 = [[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]]
bias2 = [1, 2, 3]

#layer_outputs = []
#+for neuron_weights, neuron_bias in zip(weights,bias):
 #   neuron_output = 0
 #   for n_input,weight in zip(inputs, neuron_weights):
  #      neuron_output += n_input*weight
  #  neuron_output += neuron_bias
  #  layer_outputs.append(neuron_output)


#print(layer_outputs)

In [1]:
import numpy as np 

In [ ]:
layer1_output = np.dot(inputs , np.array(weights).T) + np.array(bias)
print(layer1_output)
layer2_output = np.dot(layer1_output, np.array(weights2).T) + np.array(bias2)
print(layer2_output)

[[-2.4 -3.1  2.9]
 [-3.  -3.8  4. ]
 [-3.6 -4.5  5.1]]
[[1.01 1.23 1.45]
 [1.14 1.3  1.46]
 [1.27 1.37 1.47]]


In [ ]:
x= [[1,2,3,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8]]



class Layer_Dense:
    def __init__(self_):
        pass
    def forward(self):
        pass